parser: "@typescript-eslint/parser"
env:
    es6: true
    node: true
    browser: true
extends:
    - "eslint:recommended"
    - "prettier"
    - "prettier/@typescript-eslint"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:import/errors"
    - "plugin:import/warnings"
    - "plugin:import/typescript"
    - "airbnb-typescript/base"
    - "plugin:sonarjs/recommended"
plugins:
    - "@typescript-eslint"
    - "prettier"
    - "import"
    - "sonarjs"
parserOptions:
    ecmaVersion: 2020
    sourceType: "module"
    project: "./tsconfig.json"
settings:
    "import/ignore":
        - ".(scss|less|css)$"
rules:
    "@typescript-eslint/semi": 0
    "@typescript-eslint/indent":
        - "error"
        - 4
    "prettier/prettier":
        - "warn"
        - parser: "babel-ts"
          singleQuote: true
          semi: false
          tabWidth: 4
          printWidth: 80
          arrowParens: "avoid"
          trailingComma: "all"
    "no-process-env": "error"
    "no-confusing-arrow": "off"
    "implicit-arrow-linebreak": "off"
    "operator-linebreak":
        - "error"
        - "after"
        - overrides:
              "?": "before"
              ":": "before"
    "arrow-parens": 0
overrides:
    - files:
          - "./configs/**/*.ts"
      rules:
          "import/no-extraneous-dependencies": "off"
          "import/prefer-default-export": "off"
