parser: "@typescript-eslint/parser"
env:
    es6: true
    node: true
    browser: true
parserOptions:
    ecmaVersion: 2020
    sourceType: "module"
    project: "./tsconfig.json"
extends:
    - "eslint:recommended"
    - "airbnb-typescript/base"
    - "prettier"
    - "prettier/@typescript-eslint"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:import/errors"
    - "plugin:import/warnings"
    - "plugin:import/typescript"
    - "plugin:sonarjs/recommended"
plugins:
    - "import"
    - "prettier"
    - "sonarjs"
    - "@typescript-eslint"
settings:
    "import/ignore":
        - ".(scss|less|css)$"
rules:
    "prettier/prettier":
        - "error"
    "@typescript-eslint/semi":
        - "off"
    "@typescript-eslint/indent":
        - "off"
    "no-process-env": "error"
    "no-confusing-arrow": "off"
    "implicit-arrow-linebreak": "off"
    "operator-linebreak":
        - "error"
        - "after"
        - overrides:
              "?": "before"
              ":": "before"
    "arrow-parens": 0
overrides:
    - files:
          - "./configs/**/*.ts"
      rules:
          "import/no-extraneous-dependencies": "off"
          "import/prefer-default-export": "off"
    - files:
        - "./configs/env.ts"
      rules:
        "no-process-env": "off"
    - files:
        - "./postcss.config.js"
      rules:
        "global-require": "off"
        "@typescript-eslint/no-var-requires": "off"
